blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('hello/', views.hello_world_view),
    path('name/', views.name),
    path('photo/', views.photo),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('prog_lang.urls')),
    path('', include('relation_db.urls')),
    path('', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prog_lang/urls.py
from django.urls import path
from . import views

app_name = 'yaziki'

urlpatterns = [
    path('prog_lang/', views.ProgLangList.as_view(), name='yaziki_programmirovanie'),
    path('prog_lang/<int:id>/', views.ProgLangDetail.as_view()),
    path('prog_lang/<int:id>/delete', views.DeleteProgLangView.as_view()),
    path('prog_lang/<int:id>/edit', views.UpdateProgLangView.as_view()),

    path('create_prog_lang/', views.CreateProgLang.as_view(), name='sozdat_blog'),
    path('search/', views.Search_view.as_view()),
]

relation_db/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('all_cars/', views.relition_db)
]

relation_db/models.py
from django.db import models


# Модель many:many / ManyToMany
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class NumberCar(models.Model):
    nameCar = models.CharField(max_length=100, default='Lexus GX 570')
    number_car = models.CharField(max_length=15, default='..KG....')
    tags = models.ManyToManyField(Tag, null=True)


    def __str__(self):
        return f"{self.nameCar}------{', '.join(i.name for i in self.tags.all())}"

# модель отношение 1:1 / OneToOne
class DocumetsCar(models.Model):
    choice_car = models.OneToOneField(NumberCar, on_delete=models.CASCADE, related_name='car')
    document = models.CharField(max_length=100)

    def __str__(self):
        return self.document
    

# Модель 1:many / OneToMany
class Review(models.Model):
    # MARKS - это наше соотношение оценок, почему 2? потому что одно значение идет в бд другое на отображение
    MARKS = {
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5')
    }
    # Создаем отношение один к многим
    """
    1. первым параметром принимаем класс
    2. on_delete параметри нужен для того чтобы если удалилась машина, то и оценки удалятся
    3. realited_name параметр нужен для
    """
    choice_car = models.ForeignKey(NumberCar, on_delete=models.CASCADE, related_name='review')
    marks = models.CharField(max_length=100, choices=MARKS, default='5')
    text = models.CharField(max_length=100, default='отличная машина')
    created_at = models.DateTimeField(auto_now_add=True)

    """
    напомню что charfield нужен для хранения данных в небольшом количестве
    datetimefield с параметром auto_now_add=True, нужен для того чтобы принимать автоматически дату
    """

    def __str__(self):
        return f"Марка автомобиля {self.choice_car} Оценка: {self.marks} Комментарий к оценки {self.text}"
    

relation_db/views.py
from django.shortcuts import render
from . import models


def relition_db(request):
    if request.method == 'GET':
        nummer_car = models.NumberCar.objects.all()    
    return render(
        request,
        'relation_db.html',
        {
            'nummer_car': nummer_car
        }
    )

templates/confirm_delete.html
<p>ВЫ действительно хотите удалить язык - {{ prog_lang_id.title }}</p>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <button type="submit">Да</button>
</form>

templates/create_prog_lang.html
<center>
    <h1>Добавить язык программирования</h1>

    <form action="{% url 'yaziki:sozdat_blog' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Добавить</button>
    </form>
</center>

templates/login.html
<center>
    <h1>Авторизация</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Авторизация</button>
    </form>

    <a href="/register/">Нет аккаунта?</a>
</center>

templates/prog_lang_detail.html
<p>Количество просмотров: {{ prog_id.views }}</p>
<p>{{ prog_id.title }}</p>
<p>{{ prog_id.description }}</p>
<img src="{{ prog_id.image.url }}" alt="" width="300" height="400">
<p>{{ prog_id.create_date_lang }}</p>
<p>{{ prog_id.create_at }}</p>

templates/prog_languages.html
<center>
<button><a href="{% url 'yaziki:sozdat_blog' %}">Добавить</a></button>
<form action="/search/" method="GET">
    <input type="text" type="search" name="s" placeholder="Найти язык программирования">
    <button type="submit">Найти</button>
</form>
{% for i in prog_lang %}
<h1>{{ i.title }}</h1>
<p><a href="/prog_lang/{{ i.id }}">Подробнее</a> </p>
<p><a href="/prog_lang/{{ i.id }}/delete">Удалить</a> </p>
<p><a href="/prog_lang/{{ i.id }}/edit">Редактировать</a> </p>
{% endfor %}

<div class="pagination">
        <span class="step-links">
            {% if prog_lang.has_previous %}
                <a href="?page=1">&laquo; Первая</a>
                <a href="?page={{ prog_lang.previous_page_number }}">Предыдущая</a>
            {% endif %}

            <span class="current">
                Страница {{ prog_lang.number }} из {{ prog_lang.paginator.num_pages }}.
            </span>

            {% if prog_lang.has_next %}
                <a href="?page={{ prog_lang.next_page_number }}">Следующая</a>
                <a href="?page={{ prog_lang.paginator.num_pages }}">Последняя &raquo;</a>
            {% endif %}
        </span>
    </div>

<form action="/login/", method="post">
    {% csrf_token %}
    <button type="submit">Выйти из аккаунта</button>

</form>

</center>

templates/register.html
<center>
    <h1>Регистрация</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Регистрация</button>
    </form>
</center>

templates/relation_db.html
<h1>Список машин с тегами</h1>
{% for i in nummer_car %}

<p>{{ i.nameCar }}</p>

    {% for j in i.tags.all %}
    <p> #{{ j.name }}</p>

    {% endfor %}

{% endfor %}

templates/update_prog_lang.html
<center>
    <h1>Изменить язык программирования</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Изменить</button>
    </form>
</center>